  
CONSTRUCT_VECTOR_WITH_NUMPY(FloatVector, np.float32)
CONSTRUCT_VECTOR_WITH_NUMPY(DoubleVector, np.float)
CONSTRUCT_VECTOR_WITH_NUMPY(IntVector, np.int)

TYPEMAP_VECTOR_TO_ARRAY(double)
TYPEMAP_VECTOR_TO_ARRAY(float)
TYPEMAP_VECTOR_TO_ARRAY(int)
