  
CONSTRUCT_VECTOR_WITH_NUMPY(FloatVector, np.float32)
CONSTRUCT_VECTOR_WITH_NUMPY(DoubleVector, np.float)
CONSTRUCT_VECTOR_WITH_NUMPY(IntVector, np.int)
//CONSTRUCT_VECTOR_WITH_NUMPY(Int64Vector, np.int64)
CONSTRUCT_VECTOR_WITH_NUMPY(Int8Vector, np.int8)

TYPEMAP_VECTOR_TO_ARRAY(double)
TYPEMAP_VECTOR_TO_ARRAY(float)
TYPEMAP_VECTOR_TO_ARRAY(int)
//TYPEMAP_VECTOR_TO_ARRAY(int64_t)
TYPEMAP_VECTOR_TO_ARRAY(int8_t)
