# Centralized macros to define LLVM variables that we can leverage in components with dependencies on the emittersLib

#set(LLVM_INCLUDEROOT ${CMAKE_SOURCE_DIR}/external/llvm/include)
#set(LLVM_LIBROOT ${CMAKE_SOURCE_DIR}/external/llvm/lib)

set(LLVM_INCLUDEROOT ${CMAKE_SOURCE_DIR}/private/binaries/llvm/include)

if(MSVC)
set(LLVM_LIBROOT ${CMAKE_SOURCE_DIR}/private/binaries/llvm/Dbg/lib)
set(LLVM_LIBROOT_REL ${CMAKE_SOURCE_DIR}/private/binaries/llvm/Rel/lib)
elseif(APPLE)
endif()

if(MSVC)
# Required to compile against LLVM libraries. See LLVM documentation
if(${CMAKE_GENERATOR_TOOLSET} MATCHES "clang")
    message(STATUS "Using clang toolset")
else()
    add_compile_options(-w14062 /Zc:inline /Zc:rvalueCast /Zc:sizedDealloc-)
endif()

# Warnings that must be disabled. See LLVM documentation. 
add_compile_options(/D_SCL_SECURE_NO_DEPRECATE /D_SCL_SECURE_NO_WARNINGS)
add_compile_options( /wd4141 /wd4146 /wd4180 /wd4244 /wd4258 /wd4267 /wd4291 /wd4345 /wd4351 /wd4355 /wd4456 /wd4457 /wd4458 /wd4459 /wd4503 /wd4624 /wd4722 /wd4800 /wd4100 /wd4127 /wd4512 /wd4505 /wd4610 /wd4510 /wd4702 /wd4245 /wd4706 /wd4310 /wd4701 /wd4703 /wd4389 /wd4611 /wd4805 /wd4204 /wd4577 /wd4091 /wd4592 /wd4319 /wd4324 /wd4996)
#add_compile_options( /wd4141 /wd4146 /wd4180 /wd4244 /wd4258 /wd4267 /wd4291 /wd4345 /wd4351 /wd4355 /wd4456 /wd4457 /wd4458 /wd4459 /wd4503 /wd4624 /wd4722 /wd4800 /wd4100 /wd4127 /wd4512 /wd4505 /wd4610 /wd4510 /wd4702 /wd4245 /wd4706 /wd4310 /wd4701 /wd4703 /wd4389 /wd4611 /wd4805 /wd4204 /wd4577 /wd4091 /wd4592 /wd4319 /wd4324)
endif()

# LLVM Include files are here
include_directories(${LLVM_INCLUDEROOT})
include_directories(${LLVM_INCLUDEROOT}/llvm)
include_directories(${LLVM_INCLUDEROOT}/Support)
include_directories(${LLVM_INCLUDEROOT}/machine)
include_directories(${LLVM_INCLUDEROOT}/IR)

#=====================
# LLVM static Libraries
#=====================

link_directories(${LLVM_LIBROOT})

add_library(LLVMAnalysis STATIC IMPORTED)
set_property(TARGET LLVMAnalysis PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMAnalysis.lib)
set_property(TARGET LLVMAnalysis PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMAnalysis.lib)

add_library(LLVMAsmParser STATIC IMPORTED)
set_property(TARGET LLVMAsmParser PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMAsmParser.lib)
set_property(TARGET LLVMAsmParser PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMAsmParser.lib)

add_library(LLVMCore STATIC IMPORTED)
set_property(TARGET LLVMCore PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMCore.lib)
set_property(TARGET LLVMCore PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMCore.lib)

add_library(LLVMSupport STATIC IMPORTED)
set_property(TARGET LLVMSupport PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMSupport.lib)
set_property(TARGET LLVMSupport PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMSupport.lib)

add_library(LLVMBitWriter STATIC IMPORTED)
set_property(TARGET LLVMBitWriter PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMBitWriter.lib)
set_property(TARGET LLVMBitWriter PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMBitWriter.lib)

#=====================
# Optimizer Libs
#=====================
add_library(LLVMInstCombine STATIC IMPORTED)
set_property(TARGET LLVMInstCombine PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMInstCombine.lib)
set_property(TARGET LLVMInstCombine PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMInstCombine.lib)

add_library(LLVMTransformUtils STATIC IMPORTED)
set_property(TARGET LLVMTransformUtils PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMTransformUtils.lib)
set_property(TARGET LLVMTransformUtils PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMTransformUtils.lib)

add_library(LLVMScalarOpts STATIC IMPORTED)
set_property(TARGET LLVMScalarOpts PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMScalarOpts.lib)
set_property(TARGET LLVMScalarOpts PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMScalarOpts.lib)

#=====================
# Jitter Libs
#=====================

add_library(LLVMExecutionEngine STATIC IMPORTED)
set_property(TARGET LLVMExecutionEngine PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMExecutionEngine.lib)
set_property(TARGET LLVMExecutionEngine PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMExecutionEngine.lib)

add_library(LLVMRuntimeDyld STATIC IMPORTED)
set_property(TARGET LLVMRuntimeDyld PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMRuntimeDyld.lib)
set_property(TARGET LLVMRuntimeDyld PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMRuntimeDyld.lib)

add_library(LLVMObject STATIC IMPORTED)
set_property(TARGET LLVMObject PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMObject.lib)
set_property(TARGET LLVMObject PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMObject.lib)

add_library(LLVMMC STATIC IMPORTED)
set_property(TARGET LLVMMC PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMMC.lib)
set_property(TARGET LLVMMC PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMMC.lib)

add_library(LLVMTarget STATIC IMPORTED)
set_property(TARGET LLVMTarget PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMTarget.lib)
set_property(TARGET LLVMTarget PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMTarget.lib)

add_library(LLVMMCParser STATIC IMPORTED)
set_property(TARGET LLVMMCParser PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMMCParser.lib)
set_property(TARGET LLVMMCParser PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMMCParser.lib)

add_library(LLVMBitReader STATIC IMPORTED)
set_property(TARGET LLVMBitReader PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMBitReader.lib)
set_property(TARGET LLVMBitReader PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMBitReader.lib)

add_library(LLVMCodeGen STATIC IMPORTED)
set_property(TARGET LLVMCodeGen PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMCodeGen.lib)
set_property(TARGET LLVMCodeGen PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMCodeGen.lib)

add_library(LLVMSelectionDAG STATIC IMPORTED)
set_property(TARGET LLVMSelectionDAG PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMSelectionDAG.lib)
set_property(TARGET LLVMSelectionDAG PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMSelectionDAG.lib)

add_library(LLVMAsmPrinter STATIC IMPORTED)
set_property(TARGET LLVMAsmPrinter PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMAsmPrinter.lib)
set_property(TARGET LLVMAsmPrinter PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMAsmPrinter.lib)

add_library(LLVMX86CodeGen STATIC IMPORTED)
set_property(TARGET LLVMX86CodeGen PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMX86CodeGen.lib)
set_property(TARGET LLVMX86CodeGen PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMX86CodeGen.lib)

add_library(LLVMX86Info STATIC IMPORTED)
set_property(TARGET LLVMX86Info PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMX86Info.lib)
set_property(TARGET LLVMX86Info PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMX86Info.lib)

add_library(LLVMX86Desc STATIC IMPORTED)
set_property(TARGET LLVMX86Desc PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMX86Desc.lib)
set_property(TARGET LLVMX86Desc PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMX86Desc.lib)

add_library(LLVMX86Utils STATIC IMPORTED)
set_property(TARGET LLVMX86Utils PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMX86Utils.lib)
set_property(TARGET LLVMX86Utils PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMX86Utils.lib)

add_library(LLVMX86AsmPrinter STATIC IMPORTED)
set_property(TARGET LLVMX86AsmPrinter PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMX86AsmPrinter.lib)
set_property(TARGET LLVMX86AsmPrinter PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMX86AsmPrinter.lib)

add_library(LLVMMCDisassembler STATIC IMPORTED)
set_property(TARGET LLVMMCDisassembler PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMMCDisassembler.lib)
set_property(TARGET LLVMMCDisassembler PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMMCDisassembler.lib)

add_library(LLVMDebugInfoCodeView STATIC IMPORTED)
set_property(TARGET LLVMDebugInfoCodeView PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMDebugInfoCodeView.lib)
set_property(TARGET LLVMDebugInfoCodeView PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMDebugInfoCodeView.lib)

add_library(LLVMMCJIT STATIC IMPORTED)
set_property(TARGET LLVMMCJIT PROPERTY IMPORTED_LOCATION_DEBUG ${LLVM_LIBROOT}/LLVMMCJIT.lib)
set_property(TARGET LLVMMCJIT PROPERTY IMPORTED_LOCATION_RELEASE ${LLVM_LIBROOT_REL}/LLVMMCJIT.lib)

set(LLVM_LIBS LLVMCore LLVMAnalysis LLVMAsmParser LLVMSupport LLVMBitWriter LLVMInstCombine LLVMTransformUtils LLVMScalarOpts LLVMExecutionEngine LLVMRuntimeDyld LLVMObject LLVMMC LLVMTarget LLVMMCParser LLVMBitReader LLVMCodeGen LLVMSelectionDAG LLVMAsmPrinter LLVMX86CodeGen LLVMX86Info LLVMX86Desc LLVMX86Utils LLVMX86AsmPrinter LLVMMCDisassembler LLVMDebugInfoCodeView LLVMMCJIT)
